### ISSUE TITLE
Installation provides error regarding missing parameter.

### ISSUE THREAD

**Issue by laughnan** [kulasis/standard-edition#1]
When following the installation steps from the README, I ran into this:

```
ParameterNotFoundException

The service "kula.Core.billing.payment.merchant.VirtualMerchant" has a dependency on a non-existent parameter "virtualmerchant_url".
``` 

I think a change happened in kulasis/kulasis that we need to clean up in standard-edition.

**Comment by makoa** [comment]
Tried to reproduce error and couldn't.  Ensure app/config/parameters.yml looks like this: https://github.com/kulasis/standard-edition/blob/master/app/config/parameters.yml

**Comment by laughnan** [comment]
this is entirely possible. i had a stashed `parameters.yml` file prior to some of the changes you added in (i think i've had it for a while). i will test with the current master parameters file and follow-up.

**Comment by laughnan** [comment]
that fixed my error.
